<?php

declare(strict_types=1);

namespace Fw\Console\Commands;

use FilesystemIterator;
use Fw\Console\Application;
use Fw\Console\Command;
use Generator;
use RecursiveDirectoryIterator;
use RecursiveIteratorIterator;

/**
 * Auto-generate a project map for AI context.
 */
final class AiMapCommand extends Command
{
    protected string $name = 'ai:map';

    protected string $description = 'Auto-generate ai-app-map.md (routes → controllers → models → relationships)';

    public function __construct(Application $app)
    {
        parent::__construct($app);
    }

    public function handle(): int
    {
        $basePath = $this->app->getBasePath();
        $sections = [];

        $sections[] = '# Application Map';
        $sections[] = '';
        $sections[] = 'Auto-generated by `php fw ai:map`. Do not edit manually.';
        $sections[] = '';

        // Models
        $models = $this->scanModels($basePath);
        if (!empty($models)) {
            $sections[] = '## Models';
            $sections[] = '';
            foreach ($models as $model) {
                $sections[] = "### {$model['name']}";
                $sections[] = "- **Table:** {$model['table']}";
                $sections[] = "- **Fillable:** " . ($model['fillable'] ?: '(none)');
                if ($model['casts']) {
                    $sections[] = "- **Casts:** {$model['casts']}";
                }
                if (!empty($model['relationships'])) {
                    $sections[] = '- **Relationships:**';
                    foreach ($model['relationships'] as $rel) {
                        $sections[] = "  - `{$rel['method']}()` → {$rel['type']}";
                    }
                }
                $sections[] = '';
            }
        }

        // Routes
        $routes = $this->scanRoutes($basePath);
        if (!empty($routes)) {
            $sections[] = '## Routes';
            $sections[] = '';
            $sections[] = '| Method | URI | Action |';
            $sections[] = '|--------|-----|--------|';
            foreach ($routes as $route) {
                $sections[] = "| {$route['method']} | {$route['uri']} | {$route['action']} |";
            }
            $sections[] = '';
        }

        // Controllers
        $controllers = $this->scanControllers($basePath);
        if (!empty($controllers)) {
            $sections[] = '## Controllers';
            $sections[] = '';
            foreach ($controllers as $ctrl) {
                $sections[] = "### {$ctrl['name']}";
                $sections[] = "- **File:** {$ctrl['file']}";
                if (!empty($ctrl['methods'])) {
                    $sections[] = '- **Methods:** ' . implode(', ', $ctrl['methods']);
                }
                $sections[] = '';
            }
        }

        // FormRequests
        $requests = $this->scanRequests($basePath);
        if (!empty($requests)) {
            $sections[] = '## FormRequests';
            $sections[] = '';
            foreach ($requests as $req) {
                $sections[] = "- **{$req['name']}** — {$req['file']}";
            }
            $sections[] = '';
        }

        // Migrations
        $migrations = $this->scanMigrations($basePath);
        if (!empty($migrations)) {
            $sections[] = '## Migrations';
            $sections[] = '';
            foreach ($migrations as $migration) {
                $sections[] = "- {$migration}";
            }
            $sections[] = '';
        }

        $content = implode("\n", $sections) . "\n";
        $outputPath = $basePath . '/ai-app-map.md';
        file_put_contents($outputPath, $content);

        $this->success('Generated ai-app-map.md');
        return 0;
    }

    /**
     * @return array<array{name: string, table: string, fillable: string, casts: string, relationships: array<array{method: string, type: string}>}>
     */
    private function scanModels(string $basePath): array
    {
        $path = $basePath . '/app/Models';
        if (!is_dir($path)) {
            return [];
        }

        $models = [];

        foreach ($this->phpFiles($path) as $file) {
            $content = file_get_contents($file);
            if ($content === false || !str_contains($content, 'extends Model')) {
                continue;
            }

            $name = pathinfo($file, PATHINFO_FILENAME);
            $table = $this->extractProperty($content, 'table') ?: strtolower($name) . 's';
            $fillable = $this->extractArrayProperty($content, 'fillable');
            $casts = $this->extractArrayProperty($content, 'casts');
            $relationships = $this->extractRelationships($content);

            $models[] = [
                'name' => $name,
                'table' => $table,
                'fillable' => $fillable,
                'casts' => $casts,
                'relationships' => $relationships,
            ];
        }

        return $models;
    }

    /**
     * @return array<array{method: string, uri: string, action: string}>
     */
    private function scanRoutes(string $basePath): array
    {
        $file = $basePath . '/config/routes.php';
        if (!file_exists($file)) {
            return [];
        }

        $content = file_get_contents($file);
        if ($content === false) {
            return [];
        }

        $routes = [];
        $pattern = '/\$router->(get|post|put|patch|delete)\s*\(\s*[\'"]([^\'"]+)[\'"]\s*,\s*\[([^]]+)\]/i';

        if (preg_match_all($pattern, $content, $matches, PREG_SET_ORDER)) {
            foreach ($matches as $match) {
                $method = strtoupper($match[1]);
                $uri = $match[2];
                $action = trim($match[3]);

                // Parse [Controller::class, 'method']
                if (preg_match('/([\\\\A-Za-z]+)::class\s*,\s*[\'"]([^\'"]+)[\'"]/', $action, $m)) {
                    $action = basename(str_replace('\\', '/', $m[1])) . '@' . $m[2];
                }

                $routes[] = [
                    'method' => $method,
                    'uri' => $uri,
                    'action' => $action,
                ];
            }
        }

        return $routes;
    }

    /**
     * @return array<array{name: string, file: string, methods: array<string>}>
     */
    private function scanControllers(string $basePath): array
    {
        $path = $basePath . '/app/Controllers';
        if (!is_dir($path)) {
            return [];
        }

        $controllers = [];

        foreach ($this->phpFiles($path) as $file) {
            $content = file_get_contents($file);
            if ($content === false || !str_contains($content, 'extends Controller')) {
                continue;
            }

            $name = pathinfo($file, PATHINFO_FILENAME);
            $relative = str_replace($basePath . '/', '', $file);

            // Extract public methods
            $methods = [];
            if (preg_match_all('/public\s+function\s+(\w+)\s*\(/', $content, $matches)) {
                $methods = array_filter($matches[1], fn ($m) => $m !== '__construct');
            }

            $controllers[] = [
                'name' => $name,
                'file' => $relative,
                'methods' => $methods,
            ];
        }

        return $controllers;
    }

    /**
     * @return array<array{name: string, file: string}>
     */
    private function scanRequests(string $basePath): array
    {
        $path = $basePath . '/app/Requests';
        if (!is_dir($path)) {
            return [];
        }

        $requests = [];

        foreach ($this->phpFiles($path) as $file) {
            $name = pathinfo($file, PATHINFO_FILENAME);
            $relative = str_replace($basePath . '/', '', $file);
            $requests[] = ['name' => $name, 'file' => $relative];
        }

        return $requests;
    }

    /**
     * @return array<string>
     */
    private function scanMigrations(string $basePath): array
    {
        $path = $basePath . '/database/migrations';
        if (!is_dir($path)) {
            return [];
        }

        $migrations = [];
        foreach ($this->phpFiles($path) as $file) {
            $migrations[] = basename($file, '.php');
        }

        sort($migrations);
        return $migrations;
    }

    private function extractProperty(string $content, string $name): string
    {
        if (preg_match('/\$' . preg_quote($name) . '\s*=\s*[\'"]([^\'"]+)[\'"]/', $content, $m)) {
            return $m[1];
        }
        return '';
    }

    private function extractArrayProperty(string $content, string $name): string
    {
        if (preg_match('/\$' . preg_quote($name) . '\s*=\s*\[([^\]]*)\]/', $content, $m)) {
            return trim($m[1]);
        }
        return '';
    }

    /**
     * @return array<array{method: string, type: string}>
     */
    private function extractRelationships(string $content): array
    {
        $relationships = [];
        $types = ['BelongsTo', 'HasMany', 'HasOne', 'BelongsToMany'];

        foreach ($types as $type) {
            $pattern = '/public\s+function\s+(\w+)\s*\(\s*\)\s*:\s*' . preg_quote($type) . '/';
            if (preg_match_all($pattern, $content, $matches)) {
                foreach ($matches[1] as $method) {
                    $relationships[] = ['method' => $method, 'type' => $type];
                }
            }
        }

        return $relationships;
    }

    /**
     * @return Generator<string>
     */
    private function phpFiles(string $directory): Generator
    {
        $iterator = new RecursiveIteratorIterator(
            new RecursiveDirectoryIterator($directory, FilesystemIterator::SKIP_DOTS)
        );

        foreach ($iterator as $file) {
            if ($file->getExtension() === 'php') {
                yield $file->getPathname();
            }
        }
    }
}
