<?php

declare(strict_types=1);

namespace Fw\Console\Commands;

use Fw\Console\Command;

/**
 * SyncEnvCommand synchronizes .env keys between the backend and Vite frontend.
 */
final class SyncEnvCommand extends Command
{
    protected string $name = 'env:sync';

    protected string $description = 'Sync .env keys to frontend/.env.local with VITE_ prefix';

    public function handle(): int
    {
        $this->info('🔄 Syncing environment variables to frontend...');

        $envFile = BASE_PATH . '/.env';
        $frontendEnvFile = BASE_PATH . '/frontend/.env.local';

        if (!file_exists($envFile)) {
            $this->error('.env file not found.');
            return 1;
        }

        if (!is_dir(BASE_PATH . '/frontend')) {
            $this->warning('Frontend directory not found. Skipping sync.');
            return 0;
        }

        $lines = file($envFile, FILE_IGNORE_NEW_LINES | FILE_SKIP_EMPTY_LINES);
        $viteVars = [];

        // Define which keys should be exposed to Vite
        $exposedKeys = ['APP_NAME', 'APP_ENV', 'APP_URL'];
        $exposedPrefixes = ['API_'];

        foreach ($lines as $line) {
            if (str_starts_with($line, '#')) {
                continue;
            }

            if (str_contains($line, '=')) {
                [$key, $value] = explode('=', $line, 2);
                $key = trim($key);

                $shouldExpose = in_array($key, $exposedKeys, true);
                if (!$shouldExpose) {
                    foreach ($exposedPrefixes as $prefix) {
                        if (str_starts_with($key, $prefix)) {
                            $shouldExpose = true;
                            break;
                        }
                    }
                }

                if ($shouldExpose) {
                    $viteVars[] = "VITE_{$key}={$value}";
                }
            }
        }

        file_put_contents($frontendEnvFile, "# Auto-generated by php fw env:sync\n" . implode("\n", $viteVars) . "\n");

        $this->success("Synced " . count($viteVars) . " variables to frontend/.env.local");

        return 0;
    }
}
